// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueryParameters.Context;

#nullable disable

namespace QueryParameters.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QueryParameters.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Category 1"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Category 2"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Category 3"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Category 4"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Category 5"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Category 6"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Category 7"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Category 8"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Category 9"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Category 10"
                        },
                        new
                        {
                            CategoryId = 11,
                            Name = "Category 11"
                        },
                        new
                        {
                            CategoryId = 12,
                            Name = "Category 12"
                        },
                        new
                        {
                            CategoryId = 13,
                            Name = "Category 13"
                        },
                        new
                        {
                            CategoryId = 14,
                            Name = "Category 14"
                        },
                        new
                        {
                            CategoryId = 15,
                            Name = "Category 15"
                        },
                        new
                        {
                            CategoryId = 16,
                            Name = "Category 16"
                        },
                        new
                        {
                            CategoryId = 17,
                            Name = "Category 17"
                        },
                        new
                        {
                            CategoryId = 18,
                            Name = "Category 18"
                        },
                        new
                        {
                            CategoryId = 19,
                            Name = "Category 19"
                        },
                        new
                        {
                            CategoryId = 20,
                            Name = "Category 20"
                        },
                        new
                        {
                            CategoryId = 21,
                            Name = "Category 21"
                        },
                        new
                        {
                            CategoryId = 22,
                            Name = "Category 22"
                        },
                        new
                        {
                            CategoryId = 23,
                            Name = "Category 23"
                        },
                        new
                        {
                            CategoryId = 24,
                            Name = "Category 24"
                        },
                        new
                        {
                            CategoryId = 25,
                            Name = "Category 25"
                        },
                        new
                        {
                            CategoryId = 26,
                            Name = "Category 26"
                        },
                        new
                        {
                            CategoryId = 27,
                            Name = "Category 27"
                        },
                        new
                        {
                            CategoryId = 28,
                            Name = "Category 28"
                        },
                        new
                        {
                            CategoryId = 29,
                            Name = "Category 29"
                        },
                        new
                        {
                            CategoryId = 30,
                            Name = "Category 30"
                        },
                        new
                        {
                            CategoryId = 31,
                            Name = "Category 31"
                        },
                        new
                        {
                            CategoryId = 32,
                            Name = "Category 32"
                        },
                        new
                        {
                            CategoryId = 33,
                            Name = "Category 33"
                        },
                        new
                        {
                            CategoryId = 34,
                            Name = "Category 34"
                        },
                        new
                        {
                            CategoryId = 35,
                            Name = "Category 35"
                        },
                        new
                        {
                            CategoryId = 36,
                            Name = "Category 36"
                        },
                        new
                        {
                            CategoryId = 37,
                            Name = "Category 37"
                        },
                        new
                        {
                            CategoryId = 38,
                            Name = "Category 38"
                        },
                        new
                        {
                            CategoryId = 39,
                            Name = "Category 39"
                        },
                        new
                        {
                            CategoryId = 40,
                            Name = "Category 40"
                        },
                        new
                        {
                            CategoryId = 41,
                            Name = "Category 41"
                        },
                        new
                        {
                            CategoryId = 42,
                            Name = "Category 42"
                        },
                        new
                        {
                            CategoryId = 43,
                            Name = "Category 43"
                        },
                        new
                        {
                            CategoryId = 44,
                            Name = "Category 44"
                        },
                        new
                        {
                            CategoryId = 45,
                            Name = "Category 45"
                        },
                        new
                        {
                            CategoryId = 46,
                            Name = "Category 46"
                        },
                        new
                        {
                            CategoryId = 47,
                            Name = "Category 47"
                        },
                        new
                        {
                            CategoryId = 48,
                            Name = "Category 48"
                        },
                        new
                        {
                            CategoryId = 49,
                            Name = "Category 49"
                        },
                        new
                        {
                            CategoryId = 50,
                            Name = "Category 50"
                        },
                        new
                        {
                            CategoryId = 51,
                            Name = "Category 51"
                        },
                        new
                        {
                            CategoryId = 52,
                            Name = "Category 52"
                        },
                        new
                        {
                            CategoryId = 53,
                            Name = "Category 53"
                        },
                        new
                        {
                            CategoryId = 54,
                            Name = "Category 54"
                        },
                        new
                        {
                            CategoryId = 55,
                            Name = "Category 55"
                        },
                        new
                        {
                            CategoryId = 56,
                            Name = "Category 56"
                        },
                        new
                        {
                            CategoryId = 57,
                            Name = "Category 57"
                        },
                        new
                        {
                            CategoryId = 58,
                            Name = "Category 58"
                        },
                        new
                        {
                            CategoryId = 59,
                            Name = "Category 59"
                        },
                        new
                        {
                            CategoryId = 60,
                            Name = "Category 60"
                        },
                        new
                        {
                            CategoryId = 61,
                            Name = "Category 61"
                        },
                        new
                        {
                            CategoryId = 62,
                            Name = "Category 62"
                        },
                        new
                        {
                            CategoryId = 63,
                            Name = "Category 63"
                        },
                        new
                        {
                            CategoryId = 64,
                            Name = "Category 64"
                        },
                        new
                        {
                            CategoryId = 65,
                            Name = "Category 65"
                        },
                        new
                        {
                            CategoryId = 66,
                            Name = "Category 66"
                        },
                        new
                        {
                            CategoryId = 67,
                            Name = "Category 67"
                        },
                        new
                        {
                            CategoryId = 68,
                            Name = "Category 68"
                        },
                        new
                        {
                            CategoryId = 69,
                            Name = "Category 69"
                        },
                        new
                        {
                            CategoryId = 70,
                            Name = "Category 70"
                        },
                        new
                        {
                            CategoryId = 71,
                            Name = "Category 71"
                        },
                        new
                        {
                            CategoryId = 72,
                            Name = "Category 72"
                        },
                        new
                        {
                            CategoryId = 73,
                            Name = "Category 73"
                        },
                        new
                        {
                            CategoryId = 74,
                            Name = "Category 74"
                        },
                        new
                        {
                            CategoryId = 75,
                            Name = "Category 75"
                        },
                        new
                        {
                            CategoryId = 76,
                            Name = "Category 76"
                        },
                        new
                        {
                            CategoryId = 77,
                            Name = "Category 77"
                        },
                        new
                        {
                            CategoryId = 78,
                            Name = "Category 78"
                        },
                        new
                        {
                            CategoryId = 79,
                            Name = "Category 79"
                        },
                        new
                        {
                            CategoryId = 80,
                            Name = "Category 80"
                        },
                        new
                        {
                            CategoryId = 81,
                            Name = "Category 81"
                        },
                        new
                        {
                            CategoryId = 82,
                            Name = "Category 82"
                        },
                        new
                        {
                            CategoryId = 83,
                            Name = "Category 83"
                        },
                        new
                        {
                            CategoryId = 84,
                            Name = "Category 84"
                        },
                        new
                        {
                            CategoryId = 85,
                            Name = "Category 85"
                        },
                        new
                        {
                            CategoryId = 86,
                            Name = "Category 86"
                        },
                        new
                        {
                            CategoryId = 87,
                            Name = "Category 87"
                        },
                        new
                        {
                            CategoryId = 88,
                            Name = "Category 88"
                        },
                        new
                        {
                            CategoryId = 89,
                            Name = "Category 89"
                        },
                        new
                        {
                            CategoryId = 90,
                            Name = "Category 90"
                        },
                        new
                        {
                            CategoryId = 91,
                            Name = "Category 91"
                        },
                        new
                        {
                            CategoryId = 92,
                            Name = "Category 92"
                        },
                        new
                        {
                            CategoryId = 93,
                            Name = "Category 93"
                        },
                        new
                        {
                            CategoryId = 94,
                            Name = "Category 94"
                        },
                        new
                        {
                            CategoryId = 95,
                            Name = "Category 95"
                        },
                        new
                        {
                            CategoryId = 96,
                            Name = "Category 96"
                        },
                        new
                        {
                            CategoryId = 97,
                            Name = "Category 97"
                        },
                        new
                        {
                            CategoryId = 98,
                            Name = "Category 98"
                        },
                        new
                        {
                            CategoryId = 99,
                            Name = "Category 99"
                        },
                        new
                        {
                            CategoryId = 100,
                            Name = "Category 100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
